//! # Blacklight Error Handling
//!
//! This module extends `contract-clients-common` error handling with
//! StakingOperators-specific custom error decoding.
//!
//! ## Supported Custom Errors
//!
//! - `StakingOperatorsErrors` - Custom errors from the StakingOperators contract
//!
//! ## Usage
//!
//! ```ignore
//! use blacklight_contract_clients::common::errors::decode_any_error;
//!
//! let decoded = decode_any_error(&some_error);
//! println!("Error: {}", decoded);
//! ```

use alloy::{primitives::Bytes, sol_types::SolInterface};

// Re-export the base types and functions from the shared crate
pub use contract_clients_common::errors::{
    DecodedRevert, decode_revert, decode_revert_with_custom, extract_revert_from_contract_error,
    panic_reason, try_extract_from_string,
};

/// Re-export StakingOperators custom errors from the contract bindings.
/// These are automatically generated by the `sol!` macro from the contract ABI.
pub use crate::staking_operators::StakingOperators::StakingOperatorsErrors;

// ============================================================================
// StakingOperators Error Formatting
// ============================================================================

/// Format a StakingOperators custom error into a human-readable message.
///
/// This function provides user-friendly descriptions for each custom error
/// defined in the StakingOperators contract.
fn format_staking_error(err: &StakingOperatorsErrors) -> String {
    match err {
        StakingOperatorsErrors::DifferentStaker(_) => "Different staker".to_string(),
        StakingOperatorsErrors::InsufficientStake(_) => "Insufficient stake".to_string(),
        StakingOperatorsErrors::NoStake(_) => "No stake".to_string(),
        StakingOperatorsErrors::NoUnbonding(_) => "No unbonding request".to_string(),
        StakingOperatorsErrors::NotActive(_) => "Operator not active".to_string(),
        StakingOperatorsErrors::NotReady(_) => "Unbonding period not ready".to_string(),
        StakingOperatorsErrors::NotStaker(_) => "Not a staker".to_string(),
        StakingOperatorsErrors::OperatorJailed(_) => "Operator is jailed".to_string(),
        StakingOperatorsErrors::PendingUnbonding(_) => "Pending unbonding exists".to_string(),
        StakingOperatorsErrors::UnbondingExists(_) => "Unbonding already exists".to_string(),
        StakingOperatorsErrors::ZeroAddress(_) => "Zero address not allowed".to_string(),
        StakingOperatorsErrors::ZeroAmount(_) => "Zero amount not allowed".to_string(),
    }
}

/// Custom error decoder for StakingOperators errors.
///
/// This function attempts to decode raw bytes as a StakingOperators custom error.
fn decode_staking_error(data: &Bytes) -> Option<DecodedRevert> {
    if let Ok(err) = StakingOperatorsErrors::abi_decode(data) {
        let msg = format_staking_error(&err);
        Some(DecodedRevert::CustomError(msg))
    } else {
        None
    }
}

// ============================================================================
// Blacklight-specific Entry Points
// ============================================================================

/// Decode ANY error into a human-readable message with StakingOperators support.
///
/// This is the **main entry point** for error decoding in blacklight contracts.
/// It extends the base `decode_any_error` with StakingOperators custom error support.
///
/// # Arguments
///
/// * `error` - Any error type implementing `Display` and `Debug`
///
/// # Returns
///
/// A [`DecodedRevert`] - never panics, always returns something useful.
pub fn decode_any_error<E: std::fmt::Display + std::fmt::Debug>(error: &E) -> DecodedRevert {
    contract_clients_common::errors::decode_any_error_with_custom(error, decode_staking_error)
}

/// Decode raw revert data bytes with StakingOperators error support.
///
/// This function attempts to decode the raw bytes, including StakingOperators
/// custom errors.
pub fn decode_revert_blacklight(data: &Bytes) -> DecodedRevert {
    decode_revert_with_custom(data, decode_staking_error)
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::hex;

    /// Test decoding a custom StakingOperators error.
    ///
    /// Custom errors with no parameters only need the 4-byte selector.
    /// Selector for InsufficientStake(): cast sig "InsufficientStake()" = 0xf1bc94d2
    #[test]
    fn test_decode_staking_error() {
        // InsufficientStake() error - selector only, no params
        let data = hex::decode("f1bc94d2").unwrap();

        let decoded = decode_revert_blacklight(&Bytes::from(data));

        match decoded {
            DecodedRevert::CustomError(msg) => {
                assert_eq!(msg, "Insufficient stake");
            }
            _ => panic!("Expected CustomError, got {:?}", decoded),
        }
    }

    /// Test that standard errors still work.
    #[test]
    fn test_decode_standard_error() {
        // "test" encoded as Error(string)
        let data = hex::decode(
            "08c379a0\
             0000000000000000000000000000000000000000000000000000000000000020\
             0000000000000000000000000000000000000000000000000000000000000004\
             7465737400000000000000000000000000000000000000000000000000000000",
        )
        .unwrap();

        let decoded = decode_revert_blacklight(&Bytes::from(data));

        match decoded {
            DecodedRevert::ErrorString(msg) => {
                assert_eq!(msg, "test");
            }
            _ => panic!("Expected ErrorString, got {:?}", decoded),
        }
    }
}
